import 'package:get/get.dart';

import 'package:get/get.dart';

class LanguageTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'fr_FR': {
      'login': 'Connexion',
      'Mobile' : 'Telephone',
      'Log Out':'Déconnecter',
      'Choose Now': 'Choisissez maintenant',
      'Popular Books': 'Livres populaires',
      'UserName': 'Nom d\'utilisateur',
      'Email': 'Email',
      'Reset Password': 'Réinitialiser le mot de passe',
      'Notifications': 'Notifications',
      'Traduction': 'Traduction',
      'Select Language': 'Choisir la langue',
      'Done': 'Terminé',
      'English': 'Anglais',
      'Mobile or Phone Number':'mobile ou numero de telephone',
      'Put your Email': 'Entrer votre email',
      'Put your Name': 'Entrer votre Nom',
      'Put your Password':'Entrer votre mot de passe ',
      'Français': 'Français',
      'Reset Password': 'Réinitialiser le mot de passe',
      'Enter your new password': 'Entrez votre nouveau mot de passe',
      'New Password': 'Nouveau mot de passe',
      'Confirm Password': 'Confirmer le mot de passe',
      'Add Books': 'Ajouter des livres',
      'Forum': 'Forum',
      'Discussions': 'Discussions',
      'Write a message...': 'Écrivez un message...',
      'Send': 'Envoyer',
      'time': 'Il y a 3 jours',
      'Email or Phone number': 'E-mail ou numéro de téléphone',
      'Password': 'Mot de passe',
      'Chatbot': 'Chatbot',
      'Type a message': 'Tapez un message',
      'Enter your new password': 'Entrez votre nouveau mot de passe',
      'New Password': 'Nouveau mot de passe',
      'Confirm Password': 'Confirmer le mot de passe',
      'Add Books': 'Ajouter des livres',
      'Forum': 'Forum',
      'Discussions': 'Discussions',
      'Write a message...': 'Écrivez un message...',
      'Send': 'Envoyer',
      'time': 'Il y a 3 jours',
      'Email or Phone number': 'E-mail ou numéro de téléphone',
      'Password': 'Mot de passe',
      'Chatbot': 'Chatbot',
      'Do you have an account !':'Avez-Vous un compte',
      'Each book,a new flavor of knowledge': 'Chaque livre , une nouvelle saveur de savoir',
      'Type a message': 'Tapez un message',
      'Summary':'resumé',
      'Translating':'translater',
      'Chatting': 'discuter',
      'Choose Language' : 'Choisir une langue',
      'English': 'Anglais',
      'English(UK)':'Anglais(UK)',
      'English(US)' :'Anglais(US)',
      'Spanish' : 'Espagnol',
      'Arabic' : 'Arabe',
      'Cancel':'Annuler',
      'Log Out ' : 'Deconnecter',
      'Confirm Password': 'Confirmer le mot de passe',
      'Login': 'Se connecter',
      'Do you have an account ?': 'Avez-vous un compte ?',
      'Already have an account?': 'J\'ai déjà un compte',
      'Sign Up': 'S\'inscrire',
      'Welcome Back': 'Bienvenue à nouveau',
      'Search for books': 'Rechercher des livres',
      'Business': 'Affaires',
      'Biography': 'Biographie',
      'Novel': 'Roman',
      'Each book, a new flavor of knowledge':'Chaque livre , une nouvelle saveur de savoir',
      'History': 'Histoire',
      'Our Services': 'Nos services',
      'Chatbot IA': 'Chatbot IA',
      'Listening': 'Écouter',
      'French' : 'Français',
      'Translating': 'Traduction',
      'Summarizing': 'Résumer',
      'Popular Books': 'Livres populaires',
      'Book': 'Livre',
      'Profile':'Profil',
      'My page': 'Ma page',
      'This is a Book Page': 'Ceci est une page de livre',
      'This is a School Page': 'Ceci est une page scolaire',
      'Summary': 'Résumé',
      'Translating': 'Traduction',
      'Chatting': 'Discuter',
      'Choose Language': 'Choisir une langue',
      'English(UK)': 'Anglais (UK)',
      'English(US)': 'Anglais (US)',
      'OK':'Oui',
      'Spanish': 'Espagnol',
      'Arabic': 'Arabe',
      'Cancel': 'Annuler',
      'Log Out': 'Déconnecter',
      'Do you have an account ?': 'Avez-vous un compte ?',
      'Already have an account?': 'J\'ai déjà un compte',
      'Sign Up': 'S\'inscrire',
      'Welcome Back': 'Bienvenue à nouveau',
      'Search for books': 'Rechercher des livres',
      'Business': 'Affaires',
      'Biography': 'Biographie',
      'Novel': 'Roman',
      'Each book, a new flavor of knowledge': 'Chaque livre, une nouvelle saveur de savoir',
      'History': 'Histoire',
      'Our Services': 'Nos services',
      'Chatbot IA': 'Chatbot IA',
      'Listening': 'Écouter',
      'French': 'Français',
      'Translating': 'Traduction',
      'Summarizing': 'Résumer',
      'Popular Books': 'Livres populaires',
      'Book': 'Livre',
      'Profile': 'Profil',
      'My page': 'Ma page',
      'Welcome':'Bienvenu',
      'This is a Book Page': 'Ceci est une page de livre',
      'This is a School Page': 'Ceci est une page scolaire',
    },

    'ar_AR': {
      'Welcome':'مرحبًا',
      'Mobile': 'هاتف',
      'Profile': 'الملف الشخصي',
      'Search for books':'ابحث عن الكتب',
      'Log Out':'تسجيل الخروج',
      'Login':'تسجيل الدخول',
      'upload PDF':'رفع PDF',
      'Put your Name':'أدخل اسمك',
      'Mobile or Phone Number'  : 'رقم الهاتف أو الجوال',
      'Put your Email':'أدخل بريدك الإلكتروني',
      'Each book,a new flavor of knowledge':'كل كتاب، نكهة جديدة من المعرفة',
      'login': 'تسجيل الدخول',
      'Choose Now': 'اختر الآن',
      'Popular Books': 'الكتب الشعبية',
      'UserName': 'اسم المستخدم',
      'Email': 'البريد الإلكتروني',
      'Do you have an account !' : 'هل لديك حساب؟',
      'Reset Password': 'إعادة تعيين كلمة المرور',
      'Notifications': 'الإشعارات',
      'Traduction': 'ترجمة',
      'Select Language': 'اختر اللغة',
      'Done': 'تم',
      'English': 'الإنجليزية',
      'Français': 'الفرنسية',
      'Summary': 'ملخص',
      'Translating': 'ترجمة',
      'Chatting': 'محادثة',
      'Choose Language': 'اختر اللغة',
      'English(UK)': 'الإنجليزية (بريطانيا)',
      'English(US)': 'الإنجليزية (أمريكا)',
      'Spanish': 'الإسبانية',
      'Arabic': 'العربية',
      'Cancel': 'إلغاء',
      'Log Out': 'تسجيل الخروج',
      'Do you have an account ?': 'هل لديك حساب؟',
      'Already have an account?': 'هل لديك حساب بالفعل؟',
      'Sign Up': 'اشترك',
      'Welcome Back': 'مرحبًا بعودتك',
      'Search for books': 'ابحث عن الكتب',
      'Business': 'الأعمال',
      'Biography': 'السيرة الذاتية',
      'Novel': 'رواية',
      'Each book, a new flavor of knowledge': 'كل كتاب، نكهة جديدة من المعرفة',
      'History': 'التاريخ',
      'Our Services': 'خدماتنا',
      'Chatbot IA': 'شات بوت الذكاء الاصطناعي',
      'Listening': 'الاستماع',
      'French': 'الفرنسية',
      'Translating': 'الترجمة',
      'Summarizing': 'التلخيص',
      'Popular Books': 'الكتب الشعبية',
      'Book': 'كتاب',
      'Profile': 'الملف الشخصي',
      'My page': 'صفحتي',
      'This is a Book Page': 'هذه صفحة كتاب',
      'This is a School Page': 'هذه صفحة مدرسة',
      'OK':'تمام',

      'Put your Password': 'أدخل كلمة المرور',
      'Enter your new password': 'أدخل كلمة المرور الجديدة',
      'New Password': 'كلمة مرور جديدة',
      'Confirm Password': 'تأكيد كلمة المرور',
      'Add Books': 'إضافة كتب',
      'Forum': 'منتدى',
      'Discussions': 'مناقشات',
      'Write a message...': 'اكتب رسالة...',
      'Send': 'إرسال',
      'time': 'منذ 3 أيام',
      'Email or Phone number': 'البريد الإلكتروني أو رقم الهاتف',
      'Password': 'كلمة المرور',
      'Chatbot': 'شات بوت',
      'Type a message': 'اكتب رسالة',
      'Summary': 'ملخص',
      'Translating': 'ترجمة',
      'Chatting': 'محادثة',
      'Choose Language': 'اختر اللغة',
      'English(UK)': 'الإنجليزية (بريطانيا)',
      'English(US)': 'الإنجليزية (أمريكا)',
      'Spanish': 'الإسبانية',
      'Arabic': 'العربية',
      'Cancel': 'إلغاء',
      'Log Out': 'تسجيل الخروج',
      'Do you have an account ?': 'هل لديك حساب؟',
      'Already have an account?': 'هل لديك حساب بالفعل؟',
      'Sign Up': 'اشترك',
      'Welcome Back': 'مرحبًا بعودتك',
      'Search for books': 'ابحث عن الكتب',
      'Business': 'الأعمال',
      'Biography': 'السيرة الذاتية',
      'Novel': 'رواية',
      'History': 'التاريخ',
      'Our Services': 'خدماتنا',
      'Chatbot IA': 'شات بوت الذكاء الاصطناعي',
      'Listening': 'الاستماع',
      'French': 'الفرنسية',
      'Translating': 'الترجمة',
      'Summarizing': 'التلخيص',
      'Book': 'كتاب',
      'My page': 'صفحتي',
      'This is a Book Page': 'هذه صفحة كتاب',
      'This is a School Page': 'هذه صفحة مدرسة',
    },
  };
}


